"use strict";

const directory = require("require-dir");

const notFoundHandler = require("../helpers/handlers/notFoundHandler");

module.exports = {
    route,
};

function route(app) {
    let routes = directory("../src/routes");
    for (let i in routes) {
        app.use("/", routes[i]);
    }
    // If nothing processed from above, 404 response will be generated by notFoundHandler
    app.use("*", notFoundHandler.notFound);
}
