FROM node:15

ARG NODE_ENV=${NODE_ENV}
ARG PORT=${PORT}
ARG CIPHER_SECRET=${CIPHER_SECRET}
ARG SUPER_ADMIN_FIRST_NAME=${SUPER_ADMIN_FIRST_NAME}
ARG SUPER_ADMIN_LAST_NAME=${SUPER_ADMIN_LAST_NAME}
ARG SUPER_ADMIN_PASSWORD=${SUPER_ADMIN_PASSWORD}
ARG SUPER_ADMIN_EMAIL=${SUPER_ADMIN_EMAIL}
ARG DATABASE=${DATABASE}
ARG PG_HOST=${PG_HOST}
ARG PG_USERNAME=${PG_USERNAME}
ARG PG_DATABASE=${PG_DATABASE}
ARG PG_PASSWORD=${PG_PASSWORD}
ARG PG_PORT=${PG_PORT}
ARG REDIS_SEARCH_LOGS_QUEUE_NAME=${REDIS_SEARCH_LOGS_QUEUE_NAME}


WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install -g sequelize sequelize-cli pg
RUN npm install
RUN npm install --only=dev

COPY . .

HEALTHCHECK CMD wget -q --method=HEAD localhost:$PORT/healthcheck

EXPOSE $PORT

CMD [ "sh", "script.sh"]
