const PERCENTAGE_AGG_ALERT = "PERCENATGE AGGREGATE ALERT";
const FIRST_PUBLISHER_TAG_HIT_ALERT = "FIRST TIME LIVE PUBLISHER TAG";
const ZERO_HITS_CURRENT_HOUR_ALERT = "ZERO HITS CURRENT HOUR ALERT";
const CSV_UPLOAD_ALERT = "CSV UPLOAD ALERT";
const ADVERTISER_API_UPLOAD_ALERT = "ADVERTISER API UPLOAD AlERT";
const DEFAULT_ALERT = "DEFAULT ALERT";
const REVENUE_SHARE_SEARCH_COUNTS="REVENUE SHARE SEARCH COUNTS"

module.exports = {
    PERCENTAGE_AGG_ALERT,
    FIRST_PUBLISHER_TAG_HIT_ALERT,
    ZERO_HITS_CURRENT_HOUR_ALERT,
    CSV_UPLOAD_ALERT,
    ADVERTISER_API_UPLOAD_ALERT,
    DEFAULT_ALERT,
    REVENUE_SHARE_SEARCH_COUNTS
};
